// // General actions
// export const HANDLE_TEXT_INPUT_CHANGE = 'HANDLE_TEXT_INPUT_CHANGE';

// // loginReducer actions
// export const LOGIN_START = 'LOGIN_START';
// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// export const LOGOUT = 'LOGOUT';

// // childReducer actions
// export const FETCH_CHILDREN_START = 'FETCH_CHILDREN_START';
// export const FETCH_CHILDREN_SUCCESS = 'FETCH_CHILDREN_SUCCESS';
// export const FETCH_CHILDREN_FAILURE = 'FETCH_CHILDREN_FAILURE';

// General actions

export const HANDLE_TEXT_INPUT_CHANGE = 'HANDLE_TEXT_INPUT_CHANGE';

// registrationReducer actions

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// loginReducer actions

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// childReducer actions

export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILURE = 'FETCH_STUDENTS_FAILURE';

export const CLEAR_NEW_STUDENT_INFO = 'CLEAR_NEW_STUDENT_INFO';

export const ADD_STUDENT_START = 'ADD_STUDENT_START';
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS';
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE';

export const FETCH_SINGLE_STUDENT_START = 'FETCH_SINGLE_STUDENT_START';
export const FETCH_SINGLE_STUDENT_SUCCESS = 'FETCH_SINGLE_STUDENT_SUCCESS';
export const FETCH_SINGLE_STUDENT_FAILURE = 'FETCH_SINGLE_STUDENT_FAILURE';

export const DELETE_STUDENT_START = 'DELETE_STUDENT_START';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE';

export const POPULATE_FORM_FOR_STUDENT_UPDATE = "POPULATE_FORM_FOR_STUDENT_UPDATE";

export const UPDATE_STUDENT_START = 'UPDATE_STUDENT_START';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE';